spring.application.name=spring-db-ai
spring.ai.ollama.chat.options.model=llama3.2:latest

# Basic Connection Properties
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ecommercedb;encrypt=true;trustServerCertificate=true
spring.datasource.username=comuser
spring.datasource.password=user@123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate/JPA Specific Properties (if using Spring Data JPA)
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto=update